"""Data models used throughout the Network Security Monitor."""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional


class AlertSeverity(str, Enum):
    """Severity levels for security alerts (ordered low → high)."""

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ThreatType(str, Enum):
    """Categories of detected threats."""

    PORT_SCAN = "PORT_SCAN"
    SYN_FLOOD = "SYN_FLOOD"
    BRUTE_FORCE = "BRUTE_FORCE"
    DDOS = "DDOS"
    DNS_TUNNELING = "DNS_TUNNELING"
    SUSPICIOUS_PORT = "SUSPICIOUS_PORT"
    MALICIOUS_IP = "MALICIOUS_IP"
    PHISHING_ATTEMPT = "PHISHING_ATTEMPT"
    DATA_EXFILTRATION = "DATA_EXFILTRATION"
    UNUSUAL_TRAFFIC = "UNUSUAL_TRAFFIC"
    UNKNOWN = "UNKNOWN"


@dataclass
class Packet:
    """Normalised representation of a network packet.

    Produced by :class:`~network_security_monitor.packet_analyzer.PacketAnalyzer`
    from raw Scapy packets (or created directly in unit tests).
    """

    timestamp: float
    src_ip: str
    dst_ip: str
    protocol: str  # "TCP", "UDP", "ICMP", "DNS", "HTTP", "OTHER"
    src_port: Optional[int] = None
    dst_port: Optional[int] = None
    size: int = 0
    # TCP flags as a comma-separated string, e.g. "SYN", "SYN,ACK", "ACK"
    flags: str = ""
    # Raw payload bytes (may be empty for control packets)
    payload: bytes = b""

    # ---- convenience helpers ------------------------------------------------

    def has_flag(self, flag: str) -> bool:
        """Return ``True`` if *flag* is present in this packet's TCP flags."""
        return flag.upper() in (f.strip().upper() for f in self.flags.split(","))

    @property
    def is_syn(self) -> bool:
        return self.has_flag("SYN") and not self.has_flag("ACK")

    @property
    def is_dns(self) -> bool:
        return self.protocol == "DNS" or self.dst_port == 53 or self.src_port == 53

    def __repr__(self) -> str:
        return (
            f"Packet({self.protocol} {self.src_ip}:{self.src_port} → "
            f"{self.dst_ip}:{self.dst_port}, size={self.size})"
        )


@dataclass
class Alert:
    """A security alert generated by a :class:`~network_security_monitor.threat_detector.ThreatDetector`."""

    threat_type: ThreatType
    severity: AlertSeverity
    src_ip: str
    description: str
    timestamp: float = field(default_factory=time.time)
    dst_ip: Optional[str] = None
    dst_port: Optional[int] = None
    # Extra key/value metadata (packet count, detected ports, …)
    metadata: dict = field(default_factory=dict)

    def __str__(self) -> str:
        ts = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(self.timestamp))
        parts = [
            f"[{ts}]",
            f"[{self.severity.value}]",
            f"[{self.threat_type.value}]",
            f"src={self.src_ip}",
        ]
        if self.dst_ip:
            parts.append(f"dst={self.dst_ip}")
        if self.dst_port:
            parts.append(f"port={self.dst_port}")
        parts.append(self.description)
        return " ".join(parts)


@dataclass
class TrafficStats:
    """Aggregate traffic statistics for a monitoring window."""

    total_packets: int = 0
    total_bytes: int = 0
    tcp_packets: int = 0
    udp_packets: int = 0
    icmp_packets: int = 0
    dns_packets: int = 0
    other_packets: int = 0
    # {src_ip: packet_count}
    top_talkers: dict = field(default_factory=dict)
    # {dst_port: connection_count}
    top_ports: dict = field(default_factory=dict)
    start_time: float = field(default_factory=time.time)

    @property
    def elapsed_seconds(self) -> float:
        return time.time() - self.start_time

    @property
    def packets_per_second(self) -> float:
        elapsed = self.elapsed_seconds
        return self.total_packets / elapsed if elapsed > 0 else 0.0

    @property
    def bytes_per_second(self) -> float:
        elapsed = self.elapsed_seconds
        return self.total_bytes / elapsed if elapsed > 0 else 0.0
