"""Alert model and AlertManager for the Network Security Monitor."""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional


class AlertSeverity(Enum):
    """Severity levels for security alerts."""

    LOW = 1
    MEDIUM = 2
    HIGH = 3
    CRITICAL = 4

    def __str__(self) -> str:
        return self.name


@dataclass
class Alert:
    """Represents a single security alert generated by a detector."""

    alert_type: str
    severity: AlertSeverity
    source_ip: str
    message: str
    timestamp: datetime = field(default_factory=datetime.utcnow)
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    details: Dict = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not self.alert_type:
            raise ValueError("alert_type must not be empty")
        if not self.source_ip:
            raise ValueError("source_ip must not be empty")
        if not self.message:
            raise ValueError("message must not be empty")

    def __str__(self) -> str:
        return (
            f"[{self.severity}] {self.alert_type} | {self.source_ip} | "
            f"{self.message} @ {self.timestamp.isoformat()}"
        )


class AlertManager:
    """Stores, filters, and summarises security alerts."""

    def __init__(self) -> None:
        self._alerts: List[Alert] = []

    # ------------------------------------------------------------------
    # Mutation
    # ------------------------------------------------------------------

    def add_alert(self, alert: Alert) -> None:
        """Append a new alert to the store."""
        self._alerts.append(alert)

    def clear(self) -> None:
        """Remove all stored alerts."""
        self._alerts.clear()

    # ------------------------------------------------------------------
    # Queries
    # ------------------------------------------------------------------

    def get_alerts(
        self,
        severity: Optional[AlertSeverity] = None,
        alert_type: Optional[str] = None,
        since: Optional[datetime] = None,
        source_ip: Optional[str] = None,
    ) -> List[Alert]:
        """Return alerts matching the supplied filters (AND logic)."""
        results = self._alerts
        if severity is not None:
            results = [a for a in results if a.severity == severity]
        if alert_type is not None:
            results = [a for a in results if a.alert_type == alert_type]
        if since is not None:
            results = [a for a in results if a.timestamp >= since]
        if source_ip is not None:
            results = [a for a in results if a.source_ip == source_ip]
        return list(results)

    def get_all(self) -> List[Alert]:
        """Return all stored alerts."""
        return list(self._alerts)

    def count(self) -> int:
        """Return the total number of stored alerts."""
        return len(self._alerts)

    def get_summary(self) -> Dict:
        """Return a summary dict with counts broken down by severity and type."""
        by_severity: Dict[str, int] = {}
        by_type: Dict[str, int] = {}
        for alert in self._alerts:
            sev_key = str(alert.severity)
            by_severity[sev_key] = by_severity.get(sev_key, 0) + 1
            by_type[alert.alert_type] = by_type.get(alert.alert_type, 0) + 1
        return {
            "total": len(self._alerts),
            "by_severity": by_severity,
            "by_type": by_type,
        }

    def get_top_sources(self, n: int = 5) -> List[tuple]:
        """Return the top-n source IPs by alert count as (ip, count) tuples."""
        counts: Dict[str, int] = {}
        for alert in self._alerts:
            counts[alert.source_ip] = counts.get(alert.source_ip, 0) + 1
        return sorted(counts.items(), key=lambda x: x[1], reverse=True)[:n]
